# Generated by Django 2.2.4 on 2019-08-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BranchDetails')),
            ],
        ),
        migrations.CreateModel(
            name='MarkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject1', models.IntegerField(default=0)),
                ('Subject2', models.IntegerField(default=0)),
                ('Subject3', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StudentDetails')),
            ],
        ),
    ]
